# Uses the tag-version reusable workflow to create a tag and a github release
name: Tag and release

on:
  pull_request:
    branches:
      - 'master'
    types:
      - closed

jobs:
  tag-version:
    uses: edx/.github/.github/workflows/tag-version.yml@master
    with:
      branch: $default-branch
