name: cleanup

on:
  workflow_dispatch:
    inputs:
      repos_list:
        description: "List of repositories where you want to run the job"
        type: string
        required: true

jobs:

  split_string:
    runs-on: ubuntu-20.04

    outputs:
      output1: ${{ steps.split_string.outputs.list }}
    steps:
    - uses: actions/checkout@v2
      with:
        name: 'Jawayria/.github'

    - name: get repos list
      id: split_string
      run: echo "::set-output name=list::$(python ./.github/workflows/split_string.py ${{ github.event.inputs.repos_list }})"


  cleanup:
    runs-on: ubuntu-20.04
    needs: split_string
    strategy:
      matrix:
        repos: ${{ needs.split_string.outputs.output1}}
  #      repos: ['openedx/django-wiki', 'openedx/edx-ui-toolkit']

    steps:
      - name: print repo
        run: echo ${{ github.repository }}

      - uses: actions/checkout@v2
        with:
            name: ${{ matrix.repos }}

      - name: print repo
        run: pwd
